clan_frontend/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'domain/index'
  end

  namespace :admin do
  get 'domain/create'
  end

  namespace :admin do
  get 'domain/edit'
  end

  namespace :admin do
  get 'domain/destroy'
  end

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'home/dev_logged_in' => 'home#dev_logged_in'
  get 'home/wot_logged_in' => 'home#wot_logged_in'
  delete 'home/wot_log_out' => 'home#wot_log_out', :as => :wot_log_out

  get 'home/new_site' => 'home#new_site'
  post 'home/new_site' => 'home#new_site_create'

  get 'page/:page_name' => 'home#show_static'

  namespace 'admin' do
    scope '/:clan_id/' do
      get '/' => 'cp#index'
      resources :forum, :only => [:index, :create, :new, :destroy, :edit, :update]
      resources :acl, :only => [:index]
      resources :newsfeed, :only => [:index, :show, :new, :destroy, :edit, :create]
      resources :alliance, :only => [:index, :create, :show, :new, :destroy]

      get 'domain' => 'domain#index'
      get 'domain/custom' => 'domain#custom_domain_edit'
      post 'domain/custom' => 'domain#custom_domain_update'
      get 'domain/free' => 'domain#free_domain_edit'
      post 'domain/free' => 'domain#free_domain_update'
    end
  end

  post '/clan_search' => 'home#clan_search'
  scope '/clan/:clan_id/', :constraints => { :clan_id => /\d+/ } do
    get '/' => 'home#clan_index', :as => :clan_index
    resources :forum, :only => [:index, :show]
    scope '/forum/:forum_id/' do
      resources :thread, :only => [:index, :new, :show, :create]
      scope '/thread/:thread_id/' do
        resources :post, :only => [:create, :new]
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :post, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :cp do
  #     # Directs /cp/products/* to Admin::ProductsController
  #     # (app/controllers/cp/products_controller.rb)
  #     resources :products
  #   end
end

clan_frontend/app/views/shared/_footer.html.erb
<div class="row" style="margin-top:64px">
  <div class="col-lg-12 text-right">
    <hr />
    <p><small class="text-muted">
      &copy; 2014, <a href="http://github.com/kvakvs">Dmytro Lytovchenko</a>,
      <a href="mailto:dmytro.lytovchenko@gmail.com">email@</a>
      <br/>
      <a href="/page/about">Технические подробности реализации</a>
    </small></p>
  </div>
</div>

clan_frontend/app/views/shared/_menu_row.html.erb
<div class="row">
  <div class="col-lg-7">
    <%= link_to t('app.frontpage'), main_app.root_path,
                :class => 'btn btn-default' %>
    <% if session[:user_clan] != 'null' and
        (not session[:user_clan].nil?) and
        session[:clan_site_exists] %>
      <%= link_to t('app.forums.link'),
                  main_app.forum_index_path(session[:user_clan]),
                  :class => 'btn btn-default' %>
      <%= link_to t('app.control_panel'),
                  main_app.admin_path(session[:user_clan]),
                  :class => 'btn btn-default' %>
    <% end %>
    <% if user_signed_in? and not session[:clan_site_exists] %>
      <%= t('app.no_site_yet') %>
    <% end %>
  </div>
  <div class="col-lg-3">
    <%= render :partial => 'shared/search_form_inline' %>
  </div>

  <div class="col-lg-2 text-right">
    <!-- language -->
    <%= t 'app.lang_switch' %>
    <% if request.method == 'GET' %>
      <%= link_to 'RU', :locale => 'ru' %>
      <%= link_to 'EN', :locale => 'en' %>
    <% else %>
      <%= link_to 'RU', root_path(:locale => 'ru') %>
      <%= link_to 'EN', root_path(:locale => 'en') %>
    <% end %>
  </div><!--col-->
</div>

<div class="row">
  <div class="col-lg-12 text-right">
    <% if user_signed_in? %>
      <%=t 'app.logged_in_as' %> <strong><%= session[:user_nickname] %></strong>,
      <% if session[:user_clan] != 'null' %>
        <% if session[:is_clan_leader] %><%= t('app.leader_of_clan')
%><% else %><%= t('app.member_of_clan') %><% end %>
        [<%= session[:clan_info]['abbreviation'] %>]
        <%= session[:clan_info]['name'] %>
      <% else %>
        <%= t 'app.no_clan' %><% end %>
      <%= link_to t('app.logout'), main_app.wot_log_out_path,
                  :method => :delete, :class => 'btn btn-default' %>

    <% else %>
      <form method="post" action="https://api.worldoftanks.ru/wot/auth/login/">
        <a href="https://worldoftanks.ru/registration/ru/" class="btn btn-default"><%=t 'app.register' %></a>
        <input type="hidden" name="application_id" value="a2725c4b342fdf9977ffe92a2b84f4ee" />
        <input type="hidden" name="redirect_uri" value="<%= main_app.home_wot_logged_in_url %>" />
        <input type="hidden" name="expires_at" value="86400" />
        <input type="submit" value="<%=t 'app.login_with_wot_id' %>" class="btn btn-primary" />
        <% if Rails.env.development? %>
          <%= link_to 'Clan1',
                      home_dev_logged_in_path(:test_clan=>'1'),
                      :class => 'btn btn-warning hidden' %>
          <%= link_to 'Clan2',
                      home_dev_logged_in_path(:test_clan=>'2'),
                      :class => 'btn btn-warning hidden' %>
        <% end %>
      </form>
    <% end %>
  </div><!--col-->
</div><!--row-->

clan_frontend/app/views/shared/_page_about.html.erb
<h1>Подробности реализации</h1>

<p>Проект Clan Hosting написан с использованием таких технологий:</p>

<ul>
  <li>Ruby on Rails (без базы данных) — обеспечивает отрисовку веб-страниц,
    веб-сессии, функционал форума, шаблонизацию, перевод на несколько языков.
    Поскольку база данных встроенная в Rails не используется и общих данных
    (кроме веб сессий) не имеет, то можно запустить много копий фронта
    на нескольких серверах. Все точки входа через любой фронт независимы, за
    исключением IP адреса привязанного пользователями домена (решается правилами
    Load Balancer) и хранилища веб-сессий (доработка которого есть в TODO).</li>
  <li>Erlang (связан посредством простого RPC с Rails) — обеспечивает доступ
    Rails-фронтэнда к базе данных и контроль над операциями с базой данных,
    также может масштабироваться на несколько серверов при необходимости.</li>
  <li>Riak 2.0 — замечательная база данных типа key/value, масштабируется
    автоматически при добавлении новых серверов, перебалансируется при отказе
    серверов тоже автоматически, чтение и запись могут происходить на любом узле
    базы данных не опасаясь потерь данных при временном разделении сети.</li>
  <li>Минимальная поддержка Nginx — ориентировочно бэкенд генерирует
    конфигурационный файл для Nginx с пользовательскими доменами и затем должен
    перезапускать Nginx по мере надобности. Эта часть частично не закончена.</li>
</ul>

<h1>Замечания по функционалу</h1>

<ul>
  <li>Языки — работают английский и русский, новые добавить дело техники.</li>
  <li>Поиск кланов работает.</li>
  <li>Альянсы — частично (см. TODO ниже).</li>
  <li>Лента новостей клана — админка сделана, вывод ленты нет. См TODO.</li>
  <li>Форумы — было решено написать простейший минимальный форум самостоятельно
    по причине тяжеловесности готовых решений и сложности адаптации к работе
    без базы данных ActiveRecord (ну то есть адаптировать можно, но зачем?)</li>
  <li>Админка и система прав доступа — основа заложена, функционал
    редактирования и передачи прав не завершён.</li>
  <li>Домен пользователя или наш бесплатный поддомен — сделано кроме интеграции
    с Nginx. См. TODO по Nginx.</li>
</ul>

<h1>TODO</h1>

<p>Что можно доделать и улучшить:</p>

<ul>
  <li>OpenID — сменить форму авторизации с приложения (в браузере клиента) на
    серверную, ибо нет смысла гонять токен клиенту.</li>
  <li>Колонка новостей — сделать вывод колонки клана и возможно новостей
    альянса.</li>
  <li>Альянсы — сделано наполовину, в основном из-за сложностей в тестировании
    между несколькими кланами и нехваткой времени. То есть альянсы есть, но их
    создание не завершено и форумы полноценно не интегрированы в форумы нашего
    клана.</li>
  <li>Форумы — поскольку было решено написать простейший свой форум, то не
    хватает панели модератора, смайлов, вставки видео, изображений и проч.
    Вполне можно доработать эту часть позже.</li>
  <li>Админка — доделать функционал прав доступа.</li>
  <li>Доделать интеграцию с Nginx и перезагрузку конфига. Почти готово.</li>
  <li>Не готова стратегия работы с Load Balancer. Ожидается, что LB будет
    заниматься терминированием SSL и направлением запросов к правильному узлу
    кластера. Erlang-бэкенд может выполнять необходимые расчёты и отдавать
    команды LB.</li>
  <li>Проработать правила более-менее равномерного распределения пространства
    всех кланов между имеющимися серверами, а также процедуру перебалансировки
    и переноса точек входа доменов кланов, если один из серверов отказал. Строго
    говоря единственные данные, которые на это влияют — это хранилище сессий
    (которое можно перекинуть в Erlang или Riak и также сделать его независимым
    от точки входа) и IP адреса доменов пользователей, которые при адаптировании
    этого продукта под API хостинга можно перекидывать на новые сервера или
    переконфигурировать правила LB.</li>
  <li>Чат. Неизвестно, наколько полезно делать собственный чат, или лучше просто
    интегрироваться с существующими или с чатом в соцсетях.</li>
</ul>

clan_frontend/app/views/shared/_search_form_inline.html.erb
<!-- search -->
<%= form_tag clan_search_path, :role => 'form',
             :method => 'post', :class => 'form-inline'  do %>
  <input type="text" name="search" class="form-control" style="width: 60%"
         placeholder="<%= t 'app.search.search_box_ph' %>">
  <button type="submit" class="btn btn-default" style="width: 35%">
    <%= t 'app.search.find_btn' %></button>
<% end %>