clan_frontend/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'domain/index'
  end

  namespace :admin do
  get 'domain/create'
  end

  namespace :admin do
  get 'domain/edit'
  end

  namespace :admin do
  get 'domain/destroy'
  end

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'home/dev_logged_in' => 'home#dev_logged_in'
  get 'home/wot_logged_in' => 'home#wot_logged_in'
  delete 'home/wot_log_out' => 'home#wot_log_out', :as => :wot_log_out

  get 'home/new_site' => 'home#new_site'
  post 'home/new_site' => 'home#new_site_create'

  get 'page/:page_name' => 'home#show_static'

  namespace 'admin' do
    scope '/:clan_id/' do
      get '/' => 'cp#index'
      resources :forum, :only => [:index, :create, :new, :destroy, :edit, :update]
      resources :acl, :only => [:index]
      resources :newsfeed, :only => [:index, :show, :new, :destroy, :edit, :create]
      resources :alliance, :only => [:index, :create, :show, :new, :destroy]

      get 'domain' => 'domain#index'
      get 'domain/custom' => 'domain#custom_domain_edit'
      post 'domain/custom' => 'domain#custom_domain_update'
      get 'domain/free' => 'domain#free_domain_edit'
      post 'domain/free' => 'domain#free_domain_update'
    end
  end

  post '/clan_search' => 'home#clan_search'
  scope '/clan/:clan_id/', :constraints => { :clan_id => /\d+/ } do
    get '/' => 'home#clan_index', :as => :clan_index
    resources :forum, :only => [:index, :show]
    scope '/forum/:forum_id/' do
      resources :thread, :only => [:index, :new, :show, :create]
      scope '/thread/:thread_id/' do
        resources :post, :only => [:create, :new]
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :post, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :cp do
  #     # Directs /cp/products/* to Admin::ProductsController
  #     # (app/controllers/cp/products_controller.rb)
  #     resources :products
  #   end
end

clan_frontend/app/controllers/admin/domain_controller.rb
class Admin::DomainController < ApplicationController
  def index
    @vars = {}
    @vars[:site] = SiteModel.read(session[:user_clan])
    @vars[:free_subdomain] = free_subdomain(@vars[:site])
    @vars[:custom_domain] = custom_domain(@vars[:site])
    @vars[:clan_index] = view_context.link_to(clan_index_url, clan_index_url)
  end

  def create
  end

  def custom_domain_edit
    @vars = {}
    @vars[:site] = SiteModel.read(session[:user_clan])
    @vars[:lb_ip] = view_context.content_tag('strong', Rails.configuration.ch_lb.to_s)
  end

  def custom_domain_update
    changed_domain = self.validate_domain(params[:domain])
    unless changed_domain[0,1] =~ /[[:alpha:]]/
      redirect_to(admin_domain_free_path, :alert => t('cp.domain.must_start_with_letter'))
      return
    end
    # TODO: Check uniqueness
    SiteModel.update(session[:user_clan], {:custom_domain => changed_domain})
    redirect_to admin_domain_path, :notice => t('cp.domain.changed_alert')
  end

  def free_domain_edit
    @vars = {}
    @vars[:site] = SiteModel.read(session[:user_clan])
    @vars[:subdomain_base] = Rails.configuration.ch_subdomain_base
  end

  def free_domain_update
    changed_domain = self.validate_domain(params[:domain])
    unless changed_domain[0,1] =~ /[[:alpha:]]/
      redirect_to(admin_domain_free_path, :alert => t('cp.domain.must_start_with_letter'))
      return
    end
    # TODO: Check uniqueness
    SiteModel.update(session[:user_clan], {:free_subdomain => changed_domain})
    redirect_to admin_domain_path, :notice => t('cp.domain.changed_alert')
  end

  def destroy
  end

  def free_subdomain(site)
    free_sd = site['free_subdomain'].present? ?
        site['free_subdomain'] : t('cp.domain.yourclan')
    sub_base = Rails.configuration.ch_subdomain_base
    "#{request.protocol}#{free_sd}.#{sub_base}"
  end

  def custom_domain(site)
    custom_d = site['custom_domain'].present? ?
        site['custom_domain'] : t('cp.domain.customdomain')
    "#{request.protocol}#{custom_d}"
  end

  def validate_domain(d)
    d.truncate(128).
        gsub( /[^A-Za-z0-9\-]+/, '' ).
        gsub(/^-/, '').
        gsub(/-$/, '')
  end
end

clan_frontend/app/helpers/admin/domain_helper.rb
module Admin::DomainHelper
end

clan_frontend/app/views/admin/domain/_status_disabled.html.erb
<span class="label label-warning"><%= t('cp.domain.status_disabled') %></span>

clan_frontend/app/views/admin/domain/_status_enabled.html.erb
<span class="label label-success"><%= t('cp.domain.status_enabled') %></span>

clan_frontend/app/views/admin/domain/create.html.erb
<h1>Admin::Domain#create</h1>
<p>Find me in app/views/admin/domain/create.html.erb</p>

clan_frontend/app/views/admin/domain/custom_domain_edit.html.erb
<h1><%= t 'cp.domain.cust.edit'  %></h1>

<p><%= t 'cp.domain.cust.about1' %></p>
<p><%= raw t 'cp.domain.cust.about2', :lb_ip => @vars[:lb_ip] %></p>
<p><%= t 'cp.domain.cust.about3' %></p>

<%= form_tag admin_domain_custom_path,
             :role => 'form',
             :method => 'post' do %>
  <div class="form-group">
    <label for="domain"><%= t('cp.domain.cust.domain_field') %></label>
    <input type="text" class="form-control" id="domain" name="domain"
           placeholder="<%= t('cp.domain.cust.domain_field_hint') %>"
           value="<%= @vars[:site]['custom_domain'] %>">
  </div>
  <p><%= t 'cp.domain.alphabet' %></p>
  <button type="submit" class="btn btn-primary"><%= t('cp.domain.update') %></button>
<% end %>

clan_frontend/app/views/admin/domain/destroy.html.erb
<h1>Admin::Domain#destroy</h1>
<p>Find me in app/views/admin/domain/destroy.html.erb</p>

clan_frontend/app/views/admin/domain/free_domain_edit.html.erb
<h1><%= t 'cp.domain.subdom.edit'  %></h1>

<p><%= t 'cp.domain.subdom.about1',
         :subdomain_base => @vars[:subdomain_base] %></p>
<p><%= t 'cp.domain.subdom.about2' %></p>

<%= form_tag admin_domain_free_path,
             :role => 'form',
             :method => 'post' do %>
  <div class="form-group">
    <label for="domain"><%= t('cp.domain.subdom.domain_field') %></label>
    <input type="text" class="form-control" id="domain" name="domain"
           placeholder="<%= t('cp.domain.subdom.domain_field_hint') %>"
           value="<%= @vars[:site]['free_subdomain'] %>">
  </div>
  <p><%= t 'cp.domain.alphabet' %></p>
  <button type="submit" class="btn btn-primary"><%= t('cp.domain.update') %></button>
<% end %>

clan_frontend/app/views/admin/domain/index.html.erb
<h1><%= t 'cp.domain.manage_domain' %></h1>

<p><%= t 'cp.domain.about_short' %>
  <%= raw t('cp.domain.about_long', :clan_index => @vars[:clan_index]) %></p>

<div class="row">
  <div class="col-lg-1 dropcap"><span class="glyphicon glyphicon-home"></span></div>
  <div class="col-lg-6 vcenter">
    <%= t 'cp.domain.subdom.status' %>:
    <%= render :partial => @vars[:site]['free_subdomain'].present? ? 'status_enabled' : 'status_disabled' %>
    (<%= link_to(@vars[:free_subdomain],
                 @vars[:free_subdomain]) %>)
  </div>
  <div class="col-lg-5 text-right">
    <%= link_to t('cp.domain.configure_btn'),
                admin_domain_free_path,
                :class => 'btn btn-default' %>
  </div>
</div>

<div class="row">
  <div class="col-lg-1 dropcap"><span class="glyphicon glyphicon-globe"></span></div>
  <div class="col-lg-6 vcenter">
    <%= t 'cp.domain.cust.status' %>:
    <%= render :partial => @vars[:site]['custom_domain'].present? ? 'status_enabled' : 'status_disabled' %>
    (<%= link_to(@vars[:custom_domain], @vars[:custom_domain]) %>)
  </div>
  <div class="col-lg-5 text-right">
    <%= link_to t('cp.domain.configure_btn'),
                admin_domain_custom_path,
                :class => 'btn btn-default' %>
  </div>
</div>